-- Dynamic public website content sweep.
-- Uses the existing settings table so no new content table is required.
-- All marketing/business copy below is editable from Admin -> Settings -> Website Content.

INSERT IGNORE INTO settings (setting_group, setting_key, setting_value) VALUES
('website','nav_home_label','Home'),
('website','nav_fleet_label','Fleet'),
('website','nav_about_label','About'),
('website','nav_contact_label','Contact'),
('website','nav_account_label','My Account'),
('website','nav_bookings_label','My Bookings'),
('website','nav_book_now_label','Book Now'),

('website','hero_eyebrow','CAR HIRE IN KENYA'),
('website','hero_title','Drive your journey.'),
('website','hero_title_accent','Explore Kenya.'),
('website','hero_lead','Self-drive or chauffeur-driven, from everyday city travel to long-distance adventures.'),
('website','hero_book_label','Book Your Car'),
('website','hero_fleet_label','Explore Fleet'),
('website','hero_proof_1','Well-maintained vehicles'),
('website','hero_proof_2','Transparent rates'),
('website','hero_proof_3','Reliable customer support'),
('website','search_eyebrow','START YOUR TRIP'),
('website','search_title','Find your ride'),
('website','search_category_label','Vehicle category'),
('website','search_transmission_label','Transmission'),
('website','search_seats_label','Minimum seats'),
('website','search_price_label','Maximum price / day'),
('website','search_button_label','Search Cars'),
('website','search_note','Use the filters to narrow down the live fleet.'),

('website','trust_1_title','Well-maintained cars'),
('website','trust_1_text','Ready for your next trip'),
('website','trust_2_title','Competitive rates'),
('website','trust_2_text','Clear daily pricing'),
('website','trust_3_title','Kenya-wide service'),
('website','trust_3_text','Pickup options across Kenya'),
('website','trust_4_title','Reliable support'),
('website','trust_4_text','Help when you need it'),

('website','categories_eyebrow','BROWSE BY TYPE'),
('website','categories_title','Choose the right vehicle for your trip'),
('website','categories_text','From efficient city cars to spacious SUVs and people movers, browse the categories already available in your fleet.'),

('website','featured_eyebrow','FEATURED FLEET'),
('website','featured_title','Popular cars, presented better'),
('website','featured_text','Browse selected vehicles from our live fleet.'),
('website','featured_badge','Featured'),
('website','featured_view_label','View Car'),
('website','featured_all_label','View Full Fleet'),
('website','price_from_label','From'),
('website','price_day_label','/ day'),

('website','services_eyebrow','OUR SERVICES'),
('website','services_title','More than just a rental car'),
('website','services_text','Choose the travel option that suits your journey.'),
('website','service_1_title','Self-drive'),
('website','service_1_text','Choose your vehicle and enjoy the freedom to travel on your own schedule.'),
('website','service_2_title','Chauffeur drive'),
('website','service_2_text','Travel comfortably with a professional driver when you prefer a hands-free journey.'),
('website','service_3_title','Airport transfers'),
('website','service_3_text','Make airport arrivals and departures simple with convenient pickup arrangements.'),
('website','service_4_title','Corporate travel'),
('website','service_4_text','Practical vehicle options for meetings, projects, teams and business travel.'),

('website','why_eyebrow','THE RENTAL DIFFERENCE'),
('website','why_title','A better rental experience from search to handover.'),
('website','why_text','Discover vehicles, compare options and continue smoothly into the booking journey.'),
('website','why_1_title','Easy online discovery'),
('website','why_1_text','Find vehicles by the criteria that matter to you.'),
('website','why_2_title','Clear vehicle information'),
('website','why_2_text','See pricing and essential specifications before booking.'),
('website','why_3_title','Flexible rental journey'),
('website','why_3_text','Move naturally from vehicle selection into the booking flow.'),
('website','why_4_title','Support when you need it'),
('website','why_4_text','Customer support through your configured channels.'),
('website','why_vehicle_count_label','vehicles in the fleet'),

('website','locations_eyebrow','CAR HIRE IN KENYA'),
('website','locations_title','Hire a car where you are travelling'),
('website','locations_text','Explore locations and airport pages from our live SEO content.'),

('website','steps_eyebrow','HOW IT WORKS'),
('website','steps_title','Book in three simple steps'),
('website','steps_text','A simple journey from choosing a vehicle to collecting it.'),
('website','step_1_title','Choose your car'),
('website','step_1_text','Browse the live fleet and narrow your options using the available filters.'),
('website','step_2_title','Book your dates'),
('website','step_2_text','Select your vehicle and continue through the booking process.'),
('website','step_3_title','Collect and ride'),
('website','step_3_text','Once confirmed, complete your pickup and enjoy the journey.'),

('website','testimonials_eyebrow','WHAT CLIENTS SAY'),
('website','testimonials_title','Trusted by our customers'),

('website','reviews_eyebrow','REAL CUSTOMER FEEDBACK'),
('website','reviews_title','What our customers say'),
('website','reviews_text','Recent reviews from customers who have experienced our service.'),

('website','cta_title','Ready to start your journey?'),
('website','cta_text','Choose your vehicle and start your booking journey in minutes.'),
('website','cta_button_label','Book Your Car'),

('website','about_page_title','About Us'),
('website','about_intro_1','We are a Kenyan car rental company focused on making vehicle hire simple, dependable and convenient. Whether you need a compact hatchback for the city, a rugged 4x4 for a safari, or a chauffeur-driven sedan for an event, we help match you with the right ride.'),
('website','about_intro_2','Every vehicle in our fleet is prepared for handover and supported by a team ready to help before, during and after your journey.'),
('website','about_value_1_title','Reliable vehicles'),
('website','about_value_1_text','Vehicles are prepared and maintained for dependable travel.'),
('website','about_value_2_title','Customer support'),
('website','about_value_2_text','Reach our team through the support channels configured for the business.'),
('website','about_value_3_title','Transparent pricing'),
('website','about_value_3_text','Clear pricing and rental information before you book.'),
('website','about_cta_title','Let us get you on the road'),
('website','about_cta_text','Browse our fleet or reach out and we will help you find the right car for your trip.'),
('website','about_cta_button_label','View Fleet'),

('website','contact_page_title','Contact Us'),
('website','contact_intro_title','Get in Touch'),
('website','contact_office_label','Our Office'),
('website','contact_phone_label','Call Us'),
('website','contact_email_label','Email Us'),
('website','contact_hours_label','Working Hours'),
('website','contact_form_title','Send a Message'),
('website','contact_form_subject_placeholder','e.g. Booking enquiry'),
('website','contact_form_button_label','Send Message'),

('website','footer_brand_name',''),
('website','footer_quick_links_title','Quick Links'),
('website','footer_support_title','Support'),
('website','footer_contact_title','Get In Touch'),
('website','footer_credit','Built by AlbaTech Solutions');

SELECT 'Dynamic public website content configured.' AS status;